import { LegalLayout } from '@/components/layout/LegalLayout';

export default function TermsOfServicePage() {
  return (
    <LegalLayout title="Terms of Service" updated="June 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of StockSense AI. By creating an account or
        using the site, you agree to these Terms. Please also read our{' '}
        <a href="/legal/disclaimer" className="text-emerald font-semibold underline">Risk Disclosure</a>{' '}
        and <a href="/legal/privacy" className="text-emerald font-semibold underline">Privacy Policy</a>.
      </p>

      <h2>1. What StockSense AI Is</h2>
      <p>
        StockSense AI is an educational platform that uses AI to analyze publicly available market data for
        NSE/BSE-listed stocks and present plain-English insights, including a recommendation, technical
        analysis, F&amp;O ideas, news highlights, and risk factors. StockSense AI is{' '}
        <strong>not a SEBI-registered Investment Adviser or Research Analyst</strong>, and nothing on the
        platform is investment advice.
      </p>

      <h2>2. Eligibility &amp; Accounts</h2>
      <ul>
        <li>You must be at least 18 years old to create an account.</li>
        <li>You are responsible for keeping your login credentials secure and for all activity under your account.</li>
        <li>You agree to provide accurate information when signing up.</li>
      </ul>

      <h2>3. Paper Trading Only</h2>
      <p>
        The Portfolio feature simulates trading using virtual cash. No real money, brokerage account, or
        real securities are ever involved. StockSense AI does not execute real trades and is not a
        brokerage.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the platform for any unlawful purpose.</li>
        <li>Attempt to reverse-engineer, scrape, or overload the platform&apos;s systems.</li>
        <li>Misrepresent AI-generated content from StockSense AI as registered investment advice or research reports to others.</li>
        <li>Resell or redistribute content from the platform without permission.</li>
      </ul>

      <h2>5. No Warranty &amp; Limitation of Liability</h2>
      <p>
        StockSense AI is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of any kind. We do not
        guarantee the accuracy, completeness, or timeliness of any data, analysis, or recommendation. To the
        maximum extent permitted by law, StockSense AI and its operators shall not be liable for any losses
        — including trading or investment losses — arising from your use of, or reliance on, the platform.
      </p>

      <h2>6. AI Limitations</h2>
      <p>
        Outputs are generated by AI models (including Google Gemini) and can be wrong,
        outdated, or based on incomplete information. AI-generated content should always be treated as a
        starting point for your own research, not a final answer.
      </p>

      <h2>7. Changes to the Service</h2>
      <p>
        We may modify, suspend, or discontinue any part of StockSense AI at any time, with or without
        notice.
      </p>

      <h2>8. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the platform after changes are
        published constitutes acceptance of the revised Terms.
      </p>

      <h2>9. Governing Law</h2>
      <p>
        These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive
        jurisdiction of the courts of India.
      </p>
    </LegalLayout>
  );
}
