import { AlertTriangle } from 'lucide-react';

export function Disclaimer() {
  return (
    <div className="disclaimer" style={{ marginTop: 'var(--s5)' }}>
      <AlertTriangle width={20} height={20} style={{ flexShrink: 0, marginTop: 1 }} />
      <div>
        <p style={{ fontWeight: 600, marginBottom: 6 }}>AI-Generated Analysis — Not Verified by a Human Analyst</p>
        <p>
          This analysis is generated by AI and is for <strong>educational purposes only</strong>. It is{' '}
          <strong>not SEBI-registered investment advice</strong>. Target price and stop loss are illustrative
          estimates, not guarantees. Past performance does not guarantee future results. Stock market
          investments are subject to market risk. Please read all scheme related documents carefully and
          consult a SEBI-registered financial advisor before investing.
        </p>
      </div>
    </div>
  );
}
