export function Disclaimer() {
  return (
    <div className="mt-6 p-4 bg-amber-50 border border-amber-200 rounded-lg text-sm text-amber-800">
      <p className="font-semibold mb-1">⚠️ Important Disclaimer</p>
      <p>
        This analysis is generated by AI and is for <strong>educational purposes only</strong>. It is{' '}
        <strong>not SEBI-registered investment advice</strong>. Past performance does not guarantee
        future results. Stock market investments are subject to market risk. Please read all scheme
        related documents carefully and consult a SEBI-registered financial advisor before investing.
      </p>
    </div>
  );
}
