import Link from 'next/link';
import { TrendingUp } from 'lucide-react';

export function Footer() {
  return (
    <footer className="foot wrap">
      <div className="foot-grid">
        {/* Brand column */}
        <div>
          <div className="sb-brand" style={{ marginBottom: 0 }}>
            <span className="mark" style={{ width: 28, height: 28, borderRadius: 8 }}>
              <TrendingUp width={15} height={15} strokeWidth={2.5} />
            </span>
            <span style={{ fontSize: 17 }}>StockSense AI</span>
          </div>
          <p className="foot-about">
            AI-powered analysis for NSE/BSE stocks — clear insights, explained simply. Free, always.
          </p>
        </div>

        {/* Explore */}
        <div>
          <h5>Explore</h5>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/features">Features</Link></li>
            <li><Link href="/how-it-works">How It Works</Link></li>
            <li><Link href="/who-its-for">Who It&apos;s For</Link></li>
            <li><Link href="/get-started">Get Started</Link></li>
          </ul>
        </div>

        {/* Platform */}
        <div>
          <h5>Platform</h5>
          <ul>
            <li><Link href="/dashboard">Dashboard</Link></li>
            <li><Link href="/analysis">Analysis</Link></li>
            <li><Link href="/watchlist">Watchlist</Link></li>
            <li><Link href="/portfolio">Portfolio</Link></li>
            <li><Link href="/screener">Screener</Link></li>
            <li><Link href="/alerts">Alerts</Link></li>
          </ul>
        </div>

        {/* Legal */}
        <div>
          <h5>Legal</h5>
          <ul>
            <li><Link href="/legal/disclaimer">Risk Disclosure</Link></li>
            <li><Link href="/legal/terms">Terms of Service</Link></li>
            <li><Link href="/legal/privacy">Privacy Policy</Link></li>
          </ul>
        </div>
      </div>

      <div className="foot-legal">
        <p>
          ⚠️ StockSense AI is an educational tool only. It is not registered with SEBI as an Investment
          Adviser or Research Analyst, and nothing on this site constitutes investment advice, a research
          report, or a recommendation to buy, sell, or hold any security. Outputs are generated by an AI
          model and may be inaccurate or incomplete. Investments in securities markets are subject to
          market risk — please consult a SEBI-registered investment adviser before investing.
        </p>
        <p style={{ marginTop: 10 }}>&copy; {new Date().getFullYear()} StockSense AI. All rights reserved.</p>
      </div>
    </footer>
  );
}
