import Link from 'next/link';
import Image from 'next/image';

export function Footer() {
  return (
    <footer className="bg-(--ink) text-slate-300">
      <div className="max-w-5xl mx-auto px-4 py-12">
        <div className="flex flex-col md:flex-row md:items-start justify-between gap-8 mb-8">
          <div>
            <div className="flex items-center gap-2.5 font-display font-bold text-lg text-white mb-2">
              <Image src="/logo.svg" alt="StockSense AI" width={24} height={24} />
              <span>StockSense AI</span>
            </div>
            <p className="text-sm text-slate-400 max-w-xs">
              AI-powered analysis for NSE/BSE stocks — clear insights, explained simply.
            </p>
          </div>
          <div className="flex flex-wrap gap-x-10 gap-y-6 text-sm">
            <div>
              <p className="font-semibold text-white mb-2">Product</p>
              <ul className="space-y-1.5 text-slate-400">
                <li><Link href="/" className="hover:text-emerald-light transition-colors">Home</Link></li>
                <li><Link href="/about" className="hover:text-emerald-light transition-colors">How It Works</Link></li>
                <li><Link href="/watchlist" className="hover:text-emerald-light transition-colors">Watchlist</Link></li>
                <li><Link href="/portfolio" className="hover:text-emerald-light transition-colors">Portfolio</Link></li>
              </ul>
            </div>
            <div>
              <p className="font-semibold text-white mb-2">Legal</p>
              <ul className="space-y-1.5 text-slate-400">
                <li><Link href="/legal/disclaimer" className="hover:text-emerald-light transition-colors">Risk Disclosure</Link></li>
                <li><Link href="/legal/terms" className="hover:text-emerald-light transition-colors">Terms of Service</Link></li>
                <li><Link href="/legal/privacy" className="hover:text-emerald-light transition-colors">Privacy Policy</Link></li>
              </ul>
            </div>
          </div>
        </div>
        <div className="border-t border-white/10 pt-6 text-xs text-slate-500 space-y-2">
          <p>
            ⚠️ StockSense AI is an educational tool only. It is not registered with SEBI as an Investment
            Adviser or Research Analyst, and nothing on this site constitutes investment advice, a research
            report, or a recommendation to buy, sell, or hold any security. Outputs are generated by an AI
            model and may be inaccurate or incomplete. Investments in securities markets are subject to
            market risk — please consult a SEBI-registered investment adviser before investing.
          </p>
          <p>&copy; {new Date().getFullYear()} StockSense AI. All rights reserved.</p>
        </div>
      </div>
    </footer>
  );
}
