import { LegalLayout } from '@/components/layout/LegalLayout';

export default function RiskDisclosurePage() {
  return (
    <LegalLayout title="Risk Disclosure" updated="June 2026">
      <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800 mb-8">
        <p className="font-semibold mb-1">Not investment advice</p>
        <p>
          StockSense AI is an educational tool only. It is not registered with SEBI as an Investment
          Adviser or Research Analyst, and nothing on this site constitutes investment advice, a research
          report, or a recommendation to buy, sell, or hold any security.
        </p>
      </div>

      <h2>1. AI-Generated Content</h2>
      <p>
        Every recommendation, target price, stop loss, technical reading, F&amp;O idea, and news summary on
        this site is generated by an AI model based on historical and publicly available data. It has{' '}
        <strong>not been reviewed by a human analyst</strong> and may be inaccurate, incomplete, or
        outdated. Target prices and stop losses are illustrative estimates only — not guarantees, and not
        price targets in the sense used by a registered Research Analyst.
      </p>

      <h2>2. Market Risk</h2>
      <p>
        Investments in securities markets are subject to market risk. Prices of shares, derivatives, and
        other instruments can and do go down as well as up, and you may lose part or all of your invested
        capital. Past performance — of a stock, a strategy, or of StockSense AI&apos;s past outputs — is{' '}
        <strong>not indicative of future results</strong>.
      </p>

      <h2>3. Futures &amp; Options (F&amp;O)</h2>
      <p>
        Futures and Options trading is highly speculative and can result in the loss of your entire
        capital, and in some cases more than your initial investment. Any F&amp;O idea shown on this site is
        illustrative only and based on AI analysis of publicly available data — it is{' '}
        <strong>not a recommendation from a SEBI-registered Research Analyst</strong>. Per SEBI&apos;s own
        study, 9 out of 10 individual F&amp;O traders incur losses, with an average loss of about ₹1.1 lakh
        during FY22–FY24. Please trade only with capital you can afford to lose.
      </p>

      <h2>4. No Personalized Advice</h2>
      <p>
        StockSense AI does not consider your financial situation, risk appetite, investment objectives, or
        goals. The same output is shown to every user who searches for a given stock. This is a generic,
        educational tool — not personalized advice. Before making any investment decision, please consult
        a SEBI-registered investment adviser or research analyst.
      </p>

      <h2>5. Paper Trading Only</h2>
      <p>
        The Portfolio and Watchlist features on StockSense AI use <strong>virtual cash for paper trading
        only</strong>. No real trades are placed and no real money is ever handled by this platform.
      </p>

      <h2>6. No Guaranteed Returns</h2>
      <p>
        StockSense AI does not make, and you should not interpret anything on this site as, a promise or
        guarantee of any return, profit, or outcome. Any reference to historical accuracy of past AI
        outputs describes past performance only and is not a guarantee of future performance.
      </p>

      <h2>7. Your Responsibility</h2>
      <p>
        You are solely responsible for your own investment decisions. Please read all scheme-related
        documents and disclosures carefully, do your own research, and consult a SEBI-registered investment
        adviser before investing.
      </p>
    </LegalLayout>
  );
}
